language: python
sudo: false

python:
  - "3.6.6"


# Install the codecov pip dependency
install:
  - pip install codecov
  - pip install pytest pytest-cov
  -  python setup.py -q install

  # services:
#   - docker

# before_install:
#   - docker pull migun/metamash
#   - docker run -d -p 127.0.0.1:80:4567 migun/piret /bin/sh -c "mash --help;"
#   - docker ps -a
#   - docker run migun/metamash /bin/sh -c "cd /root; git clone https://github.com/mshakya/metamash.git; cd /root/piret/; python setup.py install; pytest --cov=./; mv coverage.txt shared"

script:
  - pytest --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov