language: python
sudo: false

python:
  - "3.6.6"

# Install miniconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b
  - ls /home
  - ls /home/travis
  - ls /home/travis/miniconda3/
  - ls /home/travis/miniconda3/bin
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # - conda update --yes conda


# Install the codecov pip dependency
install:
  - conda create --yes -n mash_env python=$TRAVIS_PYTHON_VERSION
  - source activate mash_env
  - conda install --yes -c bioconda mash -n mash_env
  - pip install codecov
  - pip install pytest pytest-cov
  - python setup.py install

script:
  - pytest --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov